Add garbage collector spec
interuss/dss pull request #465
Opened 2020-11-02 22:54 UTC by Dos-Ph

The config follows predefined-schedules format.
https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules

2020-11-02 23:01 UTC, Dos-Ph commented
.

2020-11-24 19:00 UTC, charlie-pisuraj requested changes

2020-11-24 19:00 UTC, charlie-pisuraj commented on cmds/grpc-backend/main.go
> +func createRIDServer(ctx context.Context, locality string, logger *zap.Logger, garbageColletorSpec string) (*rid.Server, error) {
Passing it around is nice its a global variable and you are accessing it in this module you can just access it directly with `*garbageCollectorSpec`

2021-11-13 00:34 UTC, BenjaminPelletier commented
PR obsolete, but issue captured in #618.

2021-11-13 00:34 UTC, closed without merging